apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bot.secretName" . }}
  labels:
    {{- include "bot.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.secret.data }}
    {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
